const {test, expect} = require('@playwright/test');

test('Verificar Conteúdo', async ({page}) => {
    await page.goto('https://www.wikipedia.org/');
    await expect(page.getByText('Wikipedia', {exact: true})).toBeVisible();
    await expect(page.getByText('The Free Encyclopedia')).toBeVisible();
    await expect(page.getByRole('link', {name: 'English 6,902,000+ articles'})).toBeVisible();
    await expect(page.getByRole('link', {name: '日本語 1,434,000+ 記事'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Deutsch 2.954.000+ Artikel'})).toBeVisible();
    await expect(page.getByRole('link', {name: '中文 1,448,000+ 条目 / 條目'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Português 1.136.000+ artigos'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'فارسی ۱٬۰۱۷٬۰۰۰+ مقاله'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Italiano 1.888.000+ voci'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Français 2 643 000+ articles'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Español 1.986.000+ artículos'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Русский 2 006 000+ статей'})).toBeVisible();
    await expect(page.getByLabel('Top languages')).toBeVisible();
    await expect(page.getByLabel('Search Wikipedia')).toBeVisible();
    await expect(page.getByRole('button', {name: 'Search'})).toBeVisible();
    await expect(page.getByRole('button', {name: 'Read Wikipedia in your'})).toBeVisible();
    await expect(page.getByRole('contentinfo').getByRole('separator')).toBeVisible();
    await expect(page.getByText('Wikipedia is hosted by the')).toBeVisible();
    await expect(page.getByRole('link', {name: 'You can support our work with'})).toBeVisible();
    await expect(page.locator('.footer-sidebar-text > .footer-sidebar-icon')).toBeVisible();
    await expect(page.getByRole('link', {name: 'Download Wikipedia for'})).toBeVisible();
    await expect(page.getByText('Save your favorite articles')).toBeVisible();
    await expect(page.getByRole('link', {name: 'Google Play Store'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Apple App Store'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Commons Free media collection'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wikibooks Free textbooks'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wikiversity Free learning'})).toBeVisible();
    await expect(page.locator('div').filter({hasText: 'Wikiversity Free learning'}).first()).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wikisource Free content'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Meta-Wiki Community'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wikivoyage Free travel guide'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wikinews Free news source'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wikiquote Free quote'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wikispecies Free species'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wiktionary Free dictionary'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wikidata Free knowledge base'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'MediaWiki Free & open wiki'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Wikifunctions Free function'})).toBeVisible();
    await expect(page.getByRole('contentinfo').getByRole('separator')).toBeVisible();
    await expect(page.getByText('This page is available under')).toBeVisible();
    await expect(page.getByRole('link', {name: 'Creative Commons Attribution-'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Terms of Use'})).toBeVisible();
    await expect(page.getByRole('link', {name: 'Privacy Policy'})).toBeVisible();
});